services:
  flask_app:
    container_name: sgi_backend
    image: tobiasvidelaug14/flask_app:1.0.0
    build: 
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - flask_db
    restart: unless-stopped
  flask_db:
    container_name: sgi_db
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    
volumes:
  pgdata: {}